version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my-network
networks:
  my-network: