version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app